---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    type: m2m
    deployer.cleanup/allow: "true"
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
